### ISSUE TITLE
Regarding the focal length and the distance between the micro-lens array and the main lens

### ISSUE THREAD

**Issue by PAKFA** [Arne-Petersen/Plenoptic-Simulation#10]
Dear Arne Petersen,

Thank you very much for your simulation of the plenoptic camera. It brings a lot of convenience to me.
Recently I am simulating some light field images for computer vision and graphics tasks. Because I am focusing on computer vision or graphics, I am not very familiar with optics, and I do not how to obtain the focal length and imaging lens between the micro-lens array and the main lens. Could you please give some suggestions?

For example, given the 'D-Gauss6 F2 43.6deg' lens, I calculate the focal length using the equation in your paper, i.e.,
f = 58.95/(1.67-1)~=87.99.
Is this calculation correct? If it is correct, what is the unit? mm, cm or others?

Additionally, assuming all lenses in the main lens as a thin lens, what is the imaging distance between the micro-lens array and the thin lens? Is the 'sensor-objective distance' in the menu?

Thank you very much!

Best regards!

**Comment by Ungetym** [comment]
Hi PAKFA,
unfortunately, this is a topic which can not simply be handled with the thin lens equation. Because of the complex lens setup of the objective, you don't have a single point or plane between the main lens and the MLA where everything is in focus regardless of the distance to the camera. Instead, you could define at which distance in front of the camera your scene objects should be in focus. This is done by setting the "Focal distance in cm" in the GUI. For points on this specific plane you could cast rays through the main lens into the camera and check, where these rays approximately converge. There currently is a naive implementation of this idea in the [raytracer.py](https://github.com/Arne-Petersen/Plenoptic-Simulation/blob/master/Blender_CamGen/raytracer.py), which calculates the "Sensor-Objective Distance in mm", i.e. the "best" position of the image sensor plane if no MLA is used. So in theory, if you turn off the MLA, and set the "Focal distance in cm", your camera should give you a sharp image of an object located at that distance. 
If you now want to use an MLA, you could set the desired microlens size and focal length and use the thin lens equation to calculate, where to move your MLA/sensor with respect to the "best sensor position" calculated before.

The reality, however, is much more complex: The rays cast from the focal plane into the camera will not converge at a single plane or point, but it will look like [the second image here](https://en.wikipedia.org/wiki/Spherical_aberration). In addition, you have effects like the [Petzval field curvature](https://en.wikipedia.org/wiki/Petzval_field_curvature) which add further inaccuracy. Furthermore, the aperture size plays a big role in focusing and using the sensor space efficiently. So my recommendation is: Use the calculated "best sensor position" as imaging plane, place your MLA/sensor relative to this position according to the thin lens equation and then start tuning the parameters by hand until you receive a clear image.

Best regards,
Tim

**Comment by Arne-Petersen** [comment]
Hi from me also
To get us in the same picture. We have to be careful with the terms we use and what we mean. At first, there are Focal Length (a fixed property of a lens) and the Focal Distance. The letter describes the point, where a camera is focused (i.e. when you use a normal camera to image a person in 2m distance). Thus, it is determined by the combination of the lens' focal length and the distance between the sensor and the lens (an object at the focus distance is imaged sharp). Basically, you use the lens' focal length and the distance you want to image sharply to compute the optimal distance between the lens and the sensor by applying the thin lens equation. So far for the standard cameras.
As for everything :-o it's more complex for the plenoptic camera. The optimal position of the sensor for a standard camera (the image of the plane in focus) no longer is the optimum for positioning the sensor. Instead the MLA has to have its focus on this distance. So you need to combine the focal length of main lens and the MLA, the distance MLA to sensor and main lens to sensor (an thus also the MLA to objective) distance. All of these are effected by aberrations and distortions and you cannot compute a meaningful setup. That's why the raytracer.py is used, to get the best guess by simulation.
At this point the simulations has the same problem as the real world. Focusing a plenoptic camera to a certain object can be very frustrating. The best way 'should' be, to use the values predicted by the python script. You will not get a sharp image directly, but you can move the sensor-MLA package (move both keeping their relative pose) to focus the object. You will have to use very small steps to get the optimal point.

Actually, this problem is one of the reasons, we developed the simulator for. Designing a plentoptic camera is a hard problem, since you have to mount (mostly hard-glue) a MLA to the sensor at a fixed distance. Then you can only pray for a usable setup. If the distance is slightly to long/short it might be impossible to get a sharp image at the desired working range. It that case, the camera is dropped in the trashcan and another setup has to be tested. This can get QUITE expensive...

Even though your problem might not be solved with my response, I hope you can get a little more insight to the plenoptic camera. It's a fascinating technique and capable of surprisingly good results (for depth estimation and image synthesis). Unfortunately, it causes some brain-pain when trying to really understand what's going on. I hope this won't let you drop you're work in this topic, it's worth the effort.

By, Arne

**Comment by PAKFA** [comment]
Dear Tim and Arne,

Thank you very much for your patience, your explanation has inspired me a lot!

In the past years, I'm focusing on light field image processing, such as the depth estimation, segmentation and view synthesis. However, all of my previous work are based on a simplified model of the Plenoptic 1.0. Recently, I realized that the model I used before is too simple, and I should bring more imaging process in the computation process. So, I find your work. It is so beautiful, and I believe that it will help my work bringing more insights to the CV/CG communities. 

I will cite your work and inform you once I have finished current research!
Finally, thanks again for your great work!

Best regards
