### ISSUE TITLE
Regarding the placement of micro-lens

### ISSUE THREAD

**Issue by PAKFA** [Arne-Petersen/Plenoptic-Simulation#13]
Dear Arne and Tim,

I have simulated a light field using the Plenoptic 1.0 model. However, it is found that the number of micro-lens is not equal to the value designed. The detail parameters are,
the sensor size is 22.68mm x 15.75mm,
the micro-lens diameter is 42um,
the sensor resolution is 3750 x 5400,
MLA Type is Rectangular layout.
According to these parameters, there are 375 x 540 micro-lenses, each micro-lens covers 10x10 pixels.
However, only 370 micro-lens appears in the rendered image.
My question is, is there a gap between the neighboring micro-lenses in the MLA?

Best regards

**Comment by PAKFA** [comment]
![test](https://user-images.githubusercontent.com/22071877/114996836-d1ca9480-9ed1-11eb-95c1-da5bc738fe09.png)
![test2](https://user-images.githubusercontent.com/22071877/114996846-d42cee80-9ed1-11eb-831a-eef9210c8958.png)

Additionally, how could I set the offset between the MLA and the sensor. I have also simulated two light fields, i.e. lf1 and lf2, with 225x225 pixels, 9x9 micro-lens, each lens cover 25x25 pixels. However, it is noticed that the offsets between the MLF and the sensor varies from lf1 to lf2, see the attached images. 
Could you please give some suggestions?

**Comment by Ungetym** [comment]
Regarding your first question:
There is no gap between the microlenses. Instead, the effect you are observing is the magnification of the MLA on the sensor. Think about a heavily simplified plenoptic camera with a pinhole instead of a main lens. Then all the light collected by the image sensor must have passed through this small pinhole. Now if you draw the schematics of this simplified camera, you can see, that the image of a single microlens on the sensor has an offset to this microlens proportional to the distance between the microlens and the camera's optical axis (or central pixel of the sensor). The same effect can be observed when using more complex models for the main lens. You can approximate the magnification factor by (distance between sensor and main lens)/(distance between MLA and main lens). However, since a realistic camera is much more complex than a pinhole camera, this is only a very rough approximation and you may have to use a more elaborated approach to find the exact magnification.

Regarding your second question:
This depends on your desired output. As I explained, this offset is the result of the magnification of the MLA, which directly depends on the distance between MLA and sensor. So you have to set a goal. E.g. do you want to have exactly 100x100 microlens images on your sensor? In this case you should start with maybe 105x105 lenses in your MLA and try to modify the setup to have an acceptable DoF range. Also as mentioned in another issue, the aperture size plays an important role. If you have a small aperture, your microlens images are limited by this aperture (you can see that the shape of the microlens images is the same as the aperture as in the images posted by you). If you have a large aperture, your microlens images might begin to overlap. In the end there is a lot of hand-tuning involved in finding a good combination of microlens parameters, MLA and sensor positioning and aperture size.

Best regards,
Tim

**Comment by PAKFA** [comment]
I see. Let me take a try.
Thank you very much!

**Comment by PAKFA** [comment]
By rendering the corresponding white image, I could find the center of each micro image and extracted 4D light field now. Thank you very much!
