### ISSUE TITLE
Could not work when the sensor-objective distance is larger than 221 mm

### ISSUE THREAD

**Issue by PAKFA** [Arne-Petersen/Plenoptic-Simulation#15]
Dear Arne and Tim,

When set the sensor-objective distance is larger than 221mm (e.g. 222, 223 or larger values), the rendered image is all black. No matter how other values are tuned, it is also black. Could you please give some suggestions?

Thank you very much!

**Comment by Ungetym** [comment]
Hi PAKFA,

maybe you have placed the sensor outside the camera housing? The solution for this should be simple - Increase the housing size by the following steps:
1. Click on "Objective Housing" (can be found in the scene tree under Camera>Housing)
2. Go to edit mode
3. Select all vertices/faces of the housing's back
4. Move the selection as far as you like

Note: Please do not delete parts of the housing, otherwise you could get additional light on your sensor which has not passed through the lenses.

If the housing is not the problem, it would be helpful to have an exemplary .blend file from you. :)

Best regards,
Tim
