### ISSUE TITLE
Cannot seem to optimise for current model, image is too dark

### ISSUE THREAD

**Issue by tswallen** [Arne-Petersen/Plenoptic-Simulation#16]
https://drive.google.com/file/d/1Lp9f-UBw_sKCZ4mWY0QwYWHijF_0l8d_/view?usp=sharing this is my file, what do I need to change in the camera? How many samples should I render with? Do you have a way of processing this image afterwards?

P.S. Hi Tim!

**Comment by Ungetym** [comment]
Hi Tom,
Google requires me to login and then tells me access denied. Could you upload the file with a less restrictive service or check the sharing properties?

**Comment by tswallen** [comment]
Sorry Tim, please try this: https://drive.google.com/file/d/1Lp9f-UBw_sKCZ4mWY0QwYWHijF_0l8d_/view?usp=sharing you can also email me, I'm keen to get back into this project :) are you using the university email?

**Comment by Ungetym** [comment]
Hi Tom, 
this link works for me. I just checked it (with Blender 2.91.2) and I think, I need further infos about what you are trying to achieve. Currently, the MLA is deactivated, so I assume you are trying to focus the main lens onto the model? I created a calibration pattern, placed it at (-0.8,0,0), so approximately at the beginning of your model and focused the camera to that distance by modifying the sensor objective distance to 123 mm. The image overall seems to be fine. A little dark maybe, but you could e.g. turn up the exposure time (Render Properties tab > Film > Exposure) if you don't want to increase your aperture size (which I would not suggest in order to keep a usable DoF).

Regarding your other questions:
 - The number of samples mainly depends on the setup and the noise level you want to achieve. For most of my work with plenoptic cameras I was satisfied with 1000-4000 samples/pixel. It also depends on the post processing. In the case of plenoptic cameras you usually want to apply some devignetting to the images, i.e. render a white image and divide your color image by the (scaled) white image. If this is your plan, there is also a little trick you can use to decrease the number of samples required: If you render the white image with the same number of samples and the same seed, it will have the same noise pattern as your main image. Accordingly, the division by the white image cancels a lot of this noise. However, in reality the static noise pattern is only a small part of the overall noise and therefore canceling most of the rendering noise by using a perfectly suitable white image would create unrealistically perfect results.
- If you want to work with plenoptic images, I can recommend my colleagues tool: https://github.com/Arne-Petersen/PlenopticImageProcessing
